### ISSUE TITLE
Repo Review

### ISSUE THREAD

**Issue by altanborali16** [altanborali16/SWE574-Group2#1]
Please review the repos of our teammates from the previous semester and share your comments.

Efe -> https://github.com/efestrikesback/SWE-573-Software-Development-Practice

Feridun -> https://github.com/Stroggification/FeridunAkyl

Yana -> https://github.com/kotobusdriver/swe573-YanaKrasovska

Enes -> https://github.com/EnesAkkal/SWE-573-Ismail-Enes-Akkal

Altan -> Created on python so no need to review

Ali -> No respond yet

**Comment by efestrikesback** [comment]
We could add @altanborali16's repo as We could also add @altanborali16's's repository to view entity designs.well to see entity designs

**Comment by efestrikesback** [comment]
We have decided on building a new backend project, majority of well established features will be exported from:

https://github.com/efestrikesback/SWE-573-Software-Development-Practice
