### ISSUE TITLE
Recommendation mechanism: backend design

### ISSUE THREAD

**Issue by kotobusdriver** [altanborali16/SWE574-Group2#10]
- [x] collect ideas for the backend design of a recommendation mechanism in the app
- [ ] formalize ideas in the requirements specification

**Comment by kotobusdriver** [comment]
![image](https://github.com/user-attachments/assets/ad499650-4751-481d-9030-5a5bb936906c)

Please see the rough idea for the recommendation system.

**Comment by efestrikesback** [comment]
1. Tag-Based Similarity Matching
Description: Communities with overlapping tags can be considered similar. The recommendation system will suggest communities that share common tags with the ones the user has already joined.
How it works:
When a user joins a community, look for other communities that have common tags with that community.
The more tags two communities share, the higher the recommendation score.
2. Steps to Implement
a. Tag Assignment to Communities
Each community will have predefined tags that represent their focus areas (e.g., #basketball, #sport, #highlights).
Ensure that each community has a set of relevant tags and allow the community creators to define these tags when setting up the community.
b. Storing Tag Data
Database Structure:
Store community information along with their associated tags in a database table (e.g., Communities and CommunityTags).
Example structure:
Communities Table: CommunityID, CommunityName
CommunityTags Table: CommunityID, Tag
You will also need a table that tracks user membership in communities:
UserCommunities Table: UserID, CommunityID
c. Tag-Based Recommendation Algorithm
Similarity Calculation:
When a user joins a community, retrieve all the tags for that community.
Query the database for other communities that share one or more of these tags.
Calculate a similarity score based on the number of common tags.
Example similarity score formula:
similarity score
=
Number of common tags
Total tags in both communities
similarity score= 
Total tags in both communities
Number of common tags
​
 
Recommendation Process:
When a user joins or interacts with a community (e.g., BasketballLovers), retrieve the tags of the joined community (#basketball, #sport, #highlights).
Find other communities that have one or more of these tags (e.g., FootballFans has #sport, #football, #discussion).
Rank these communities by the number of matching tags and suggest the ones with the highest similarity score.

**Comment by kotobusdriver** [comment]
Agreed and recorded in Designs section at https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios#recommendation-service-backend-design
