### ISSUE TITLE
Discussion: "We are using too many resources developing two backends at the same, let's choose one, and move on"

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#104]
Our first decision was to build a backend from scratch (component: original backend)

After the first customer review, we decided to try our chance with Yana's project as well. @kotobusdriver kept developing her backend (component: backend) during the period of _REFORM_ (two-week extension) to meet customer requirements.

In the meantime, we also decided to keep building the original backend therefore I (@efestrikesback) kept building. 

Please write your thoughts as comments, I want to make sure that after Customer Presentation v.2 Deliverables, we use our developer resources much more efficiently.

@kotobusdriver  could you please add the outcome of the decision to our document? 
thanks in advance
-efe

**Comment by EnesAkkal** [comment]
I think both backend developments  should continue for a while to provide us with the flexibility to choose the best option. Additionally, we should hold weekly discussions to review the current status of each backend development and assess our progress. However, at certain point, we should go with only one backend project only as we are trying to implement features before the deadline.

**Comment by kotobusdriver** [comment]
As it appears that the development will be FE-driven,  it does not really matter which BE we work with: it is my understanding, that the JSON structure used for the current FE does not entirely match either of the existing two BEs. 
Of course, concentrating on one BE is more productive (as we discussed, @efestrikesback). Whoever takes the lead, should act as a de facto team lead and introduce others to the general design, data flow, database structure, and APIs. It would also make sense that the team lead formulates and assigns tasks to the team.

**Comment by efestrikesback** [comment]
@kotobusdriver could you please add the decision to the wiki and close the issue, thanks.

**Comment by kotobusdriver** [comment]
The alternative backend developed by Yana as a fall-back alternative will be discontinued. See appropriate decision captured in https://github.com/altanborali16/SWE574-Group2/wiki/Decisions-&-Policies
