### ISSUE TITLE
Discussion: "We have decided to give absolute authority to @efestrikesback during two-week REFORM period, should we move on centralized leadership or return back to more democratic ways?""

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#105]
During two-week period we have restricted issue creation, branch creation and code merge.
We also decided to skip lengthy meetings to completely focus on development. 
Lastly, we gave full authority to me (@efestrikesback ) to assign and create tasks.
Let's decide on our future for the upcoming weeks.
Please write your thoughts as comments.

@kotobusdriver could you please add the outcome of the decision to our document?
thanks in advance
-efe

**Comment by kotobusdriver** [comment]
As I mentioned [here](https://github.com/altanborali16/SWE574-Group2/issues/104#issuecomment-2453409005), we need a team lead to onboard the team and guide the development.

**Comment by AliSerGok** [comment]
I think to give authority to @efestrikesback will be better

**Comment by efestrikesback** [comment]
@kotobusdriver could you please add the decision to the wiki and close the issue, thanks.

**Comment by kotobusdriver** [comment]
The team chose to give authority to Efe as backend architect to be a team lead and assign/create tasks related to product development.
Appropriate decision captured in https://github.com/altanborali16/SWE574-Group2/wiki/Decisions-&-Policies
