### ISSUE TITLE
[BUG]: create template button goes out of screen and disappears as we add more fields 

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#113]
I will review and merge the feature branch and do the feature testing. @efestrikesback 
@altanborali16 will fix the bug. 

We probably need to resize the template and create a modal. Or make the container use widening properties.

**Comment by altanborali16** [comment]
@AliSerGok will fix the bug, please contact with @efestrikesback about branches

**Comment by efestrikesback** [comment]
@AliSerGok any update?

**Comment by AliSerGok** [comment]
@efestrikesback This bug has been resolved
