### ISSUE TITLE
[BUG]: under community page, recently created post do not show up 

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#114]
Add page refresh OR second fetch to show recently created post.

**Comment by altanborali16** [comment]
@AliSerGok will fix the bug, please contact with @efestrikesback about branches

**Comment by AliSerGok** [comment]
@efestrikesback  this bug has been fixed at the commit : e6022f493adf4f0de460738dc630498f45dd1525
