### ISSUE TITLE
Add action flows for: like, commenting, numerically filtered advanced search, comments, comments on comments

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#118]
- [x] User likes a post

- [x] See users who like the post

- [x] Use advanced search numerically filtering feature

- [x] User comments on a post 

- [x] User comments on a comment

@AliSerGok please finish before your holiday leave, @EnesAkkal please support @AliSerGok and review the work.

**Comment by AliSerGok** [comment]
Advance Search Event Flow diagram was changed and detailed according to new features like comment search, template numerical and geological filtering etc. at [Event Flow Diagrams](https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios#event-flow-diagrams)

**Comment by AliSerGok** [comment]
Work Flow diagrams for 
 -User likes a post
 -See users who like the post
 -User comments on a post
 -User comments on a comment
 actions created. at [Event Flow Diagrams](https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios#event-flow-diagrams)
