### ISSUE TITLE
Add mockups for: like, commenting, numerically filtered advanced search, comments, comments on comments

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#119]
@EnesAkkal  please put the link to your designs as a comment to this issue. Tag me and let me know when you finish, thanks.

**Comment by EnesAkkal** [comment]
New mockup screens have been designed. 

1. Advanced Search

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/ed116ab1-c6e8-4cd5-b408-bc6417079b85">

2. Post screen with like,comments and comment on comments
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/92d3cec2-8e33-4a77-bd30-d590c73b1703">

**Comment by efestrikesback** [comment]
Thanks, please make sure you add them to the wiki as well. Then you may close the issue without my approval @EnesAkkal

**Comment by EnesAkkal** [comment]
Issue has been closed, new mockups screens can be seen at [here](https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios#ui-mockup-designs).
