### ISSUE TITLE
Badge system: backend design 

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#12]

**Comment by kotobusdriver** [comment]
![image](https://github.com/user-attachments/assets/bc2b601b-8cae-4aa0-9b18-cf68bb710aee)

Please see the domain model for the suggested badge system. It accommodates both community-level and a global score for the users. This score may be used to determine the badge appearance (copper, silver, gold etc).

**Comment by kotobusdriver** [comment]
Agreed and documented in Designs section here - https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios#badge-system-backend-design
