### ISSUE TITLE
Documentation & wiki maintenance (till MVP)

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#120]
Yana spent a lot of time on wiki and documentation. 

@kotobusdriver 's wiki works will be sub-issues under this issue.

**Comment by efestrikesback** [comment]
@kotobusdriver can you please add your work as short comments here, thanks.

Like 

-updated requirements page

-added X decision etc

**Comment by kotobusdriver** [comment]
Updated https://github.com/altanborali16/SWE574-Group2/wiki/Decisions-&-Policies
Updated https://github.com/altanborali16/SWE574-Group2/wiki/Meeting-notes

**Comment by kotobusdriver** [comment]
Updated requirements with details on recommendation system and advanced search - https://github.com/altanborali16/SWE574-Group2/wiki/Requirements-Specification

**Comment by kotobusdriver** [comment]
Started milestone 2 report - https://github.com/altanborali16/SWE574-Group2/wiki/Milestone-2-report
