### ISSUE TITLE
Implement advanced search 

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#124]

**Comment by efestrikesback** [comment]
Altan will be reviewing the code

**Comment by AliSerGok** [comment]
Advanced Search feature was created for community page commit number: 131901996f82250ee9616e307283bc33d1936bb
- Basic Search 
- Post Fields Search
- Template Fields Search

**Comment by AliSerGok** [comment]
Search Engine feature was created. commit number: ea577018e27aa5155ccddc421b8d49943b3df6ba

**Comment by AliSerGok** [comment]
postSearch end templateSearch engine pages were created. commit number: ac9a344982ebd12948a5c016809a40b687d0d8d7

**Comment by AliSerGok** [comment]
showResulsPage feature was created. commit number: e00616414fc2b2226705197d87631f7d571a2aca

**Comment by AliSerGok** [comment]
Comment Search and User Search features were created.  commit number: 749f1efbb7c95a7af20f9bd0aeab65759824b9fb

**Comment by AliSerGok** [comment]
posıtıve number field improvement created by Altan. commıt number: 812aa2a6a8c5e36a40c80bfed45b52e663f59e17

**Comment by AliSerGok** [comment]
The advance search feature was tested and no problems were found.
