### ISSUE TITLE
Modify Advanced Search Mockup

### ISSUE THREAD

**Issue by EnesAkkal** [altanborali16/SWE574-Group2#125]
Advanced search mockup needs to be modified, the existing one here https://github.com/altanborali16/SWE574-Group2/issues/119#issuecomment-2466499280 will be modified.

The numeric fields will be updated and following operators will be added.

* exact

* less than or equal

* greater than or equal

* between a lower and an upper bound.

**Comment by efestrikesback** [comment]
Great, thanks.
