### ISSUE TITLE
[BUG]: Unable to create community with long descriptions

### ISSUE THREAD

**Issue by EnesAkkal** [altanborali16/SWE574-Group2#127]
When attempting to create a community with a long description, a 403 Forbidden error is returned from the server. Shorter descriptions work as expected, but longer ones consistently trigger this error.  The character limit of all string fields in the project should be increased as to avoid this problem. 

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/6bf2e88b-2156-411f-8ba2-854fed54ab45">

**Comment by kotobusdriver** [comment]
This requires changes to the existing components.
@efestrikesback

**Comment by efestrikesback** [comment]
I will check it out, asap.

**Comment by efestrikesback** [comment]
My first guess is that it is related to DB's varchar limit.

**Comment by altanborali16** [comment]
Problem solved with  [Commit 4256f46](https://github.com/altanborali16/SWE574-Group2/commit/4256f465cbb3b749c416e270363aa790a25f22de) on frontend with char size limit
