### ISSUE TITLE
Implement recommendation system

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#133]
@altanborali16 will help with the backend design
@kotobusdriver will research and develop

**Comment by efestrikesback** [comment]
Please make sure that you and Altan agree on the design together before starting.

Simplest form

recommend by upvote count

recommend by community tag (if the post is shared in a community related to your memberships)

start by designing simple endpoints 

For example 

/HotPostFromAllCommunities returns post list with 10+ like counts from all the communities   

/RecommendedPostsByInterest returns random posts from related communities

**Comment by kotobusdriver** [comment]
WIP: endpoint and query for communities recommended by liked post and matched tags - [446f32f](https://github.com/altanborali16/SWE574-Group2/commit/446f32f254f065689f9c0cf8adadd8d9b28f875a)

**Comment by altanborali16** [comment]
I cannot close the issue because when it is tested backend does not work.

**Comment by altanborali16** [comment]
Critical label has been added

**Comment by altanborali16** [comment]
For the MVP some sort of recommendation has been implemented

**Comment by kotobusdriver** [comment]
The current backend implementation returns posts from communities where the user is not a member but posts from which the user liked. The implementation is based on the tag similarity between recommended communities and the communities the user created. Feature API tested for correct performance before pull request, added to the Postman collection, and feature tested yesterday on the deployed application. 
![image](https://github.com/user-attachments/assets/328c34e2-0734-447d-8a57-d3a1c2f77d74)

Improvements to the feature are possible after the MVP stage.
