### ISSUE TITLE
[Decision]: Filtering at frontend, Efe returns as backend developer for a week

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#134]
@kotobusdriver please shortly explain and add these to our decisions page, thanks.

**Comment by kotobusdriver** [comment]
https://github.com/altanborali16/SWE574-Group2/wiki/Meeting-notes#november-17-2024
https://github.com/altanborali16/SWE574-Group2/wiki/Decisions-&-Policies#development-decisions
