### ISSUE TITLE
Upvotes frontend

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#138]

**Comment by altanborali16** [comment]
@EnesAkkal has implemented this feature with [Commit 61ccf51](https://github.com/altanborali16/SWE574-Group2/commit/61ccf51d6d694d854dc757af53891d0fcc94174f) so I am closing the issue

**Comment by EnesAkkal** [comment]
This feature has been implemented with commit number 3b90c897739700f9d3bba03eb55fbe9f52639deb as well.
