### ISSUE TITLE
Documenting meeting notes, October 1, 2024 

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#14]

**Comment by efestrikesback** [comment]
@kotobusdriver  could you please review and format (if you find it necessary) and close the commit? 

I have added the notes to the pages given below:
https://github.com/altanborali16/SWE574-Group2/wiki/Meeting-notes
https://github.com/altanborali16/SWE574-Group2/wiki/Elicitation-Notes#30092024-2nd-week

**Comment by kotobusdriver** [comment]
Elicitation notes and requirements specification updated
