### ISSUE TITLE
Badge system: frontend design

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#15]
Let's put our design drawings/sketchers here, and have our discussion as comments under this issue.

**Comment by EnesAkkal** [comment]
You can see some of the designed screens below. 

**Login / Register Screen**

<img width="795" alt="image" src="https://github.com/user-attachments/assets/e8ee1088-fa69-4690-badb-6f0ec2df4cb8">


**Communities Screen**

<img width="796" alt="image" src="https://github.com/user-attachments/assets/ca613255-61ae-40c9-a57d-56919fb78ae4">

**Create Community Screen**

<img width="795" alt="image" src="https://github.com/user-attachments/assets/732329d4-88f0-49e9-91e1-32cfbc3d42a6">

**Community Feed Screen**

<img width="787" alt="image" src="https://github.com/user-attachments/assets/7af34539-48c0-44db-a896-515dfc69dda4">

**Comment by EnesAkkal** [comment]
An example of badge system design for communities can be seen below. 
<img width="910" alt="image" src="https://github.com/user-attachments/assets/acd8d556-1eab-4f68-af0e-9d7b9f80cf98">
