### ISSUE TITLE
[BUG] Reply and comment difference on response

### ISSUE THREAD

**Issue by altanborali16** [altanborali16/SWE574-Group2#151]
![image](https://github.com/user-attachments/assets/ec32e3a0-81e0-496d-9deb-f1bcb3d21d91)

As you can see reply is shown both reply and comment, we need to think about how to solve it, I mean on backend or frontend.

**Comment by EnesAkkal** [comment]
This bug has been fixed with commit number 4acd5c06598911841dfe9dd79d1ce323905e174b.

**Comment by altanborali16** [comment]
It is checked and pull request has been accepted so closing issue
