### ISSUE TITLE
Recommendations update

### ISSUE THREAD

**Issue by altanborali16** [altanborali16/SWE574-Group2#155]
As you mention @kotobusdriver it was working on your local, could you also please test in new versions, also need to add recommendations for the new user(no community created or subscribed) and can you explain how recommendations work, only community tags are enough ? should user need to upvote or comment on posts ? etc..

**Comment by kotobusdriver** [comment]
@altanborali16 I may be wrong but it looks like the frontend does not call the /posts/recommendations endpoint at the moment. Is that so?

**Comment by altanborali16** [comment]
@kotobusdriver you are right because when i tested there were no recommendations for the user which we talked, after that I created a community with tags, and there is a community which has a similar tags and user does not get any recommendations , I also informed that in the group whtasapp but cannot get any response so I need to create something for the mvp. Here are the pictures of community examples.  
![image](https://github.com/user-attachments/assets/c0f3dad1-c7db-4c37-8d37-92b0f6a602e9)
![image](https://github.com/user-attachments/assets/8f63b3b9-c90c-4638-9139-acd07e83e73b)

When I run the apis for recommendation I get [] as response. I might did something wrong. From your response I understand that user needs to like posts which I am not aware of. But anyways I think subscribed communities and created communities should be also be considered.

Currently posts does not have tags, it has on database but it is not implemented on frontend. Should posts needs tags ?

**Comment by kotobusdriver** [comment]
I would say that posts don't need tags, but this can be discussed.
The crucial point is that now the 
I'll modify the recommendation logic to include matching tags from subscribed or created communities.

**Comment by altanborali16** [comment]
with full functionality it will be done by 5th December evening as discussed with @kotobusdriver

**Comment by kotobusdriver** [comment]
recommendations branch updated as discussed - https://github.com/altanborali16/SWE574-Group2/commit/084d67a57d417e3aadde6caee306e8bd11cc5dee
