### ISSUE TITLE
Populate badges and give info to user how to earn a new one

### ISSUE THREAD

**Issue by altanborali16** [altanborali16/SWE574-Group2#156]

**Comment by altanborali16** [comment]
assigned to @EnesAkkal with upgraded css

**Comment by EnesAkkal** [comment]
This feature has been added with commit number e6d7099e9f201e7b9b7326fbb2b191bdddeaf2b8 and 1cd80bd8da9f786658c1acbab3b9f2607b3da38a. Badge images also have been revised to have a more friendly UI. Can you close the issue @altanborali16  ?

**Comment by altanborali16** [comment]
it is working
