### ISSUE TITLE
Recommendation system: frontend design

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#16]

**Comment by EnesAkkal** [comment]
The recommendation system will appear under the "Communities" tab, offering users personalized suggestions. The design will allow users to browse through various categories, such as "Recommended for You," "Invite Only," "Trending," "Newest," and "Oldest," as seen in the mockup.

<img width="841" alt="image" src="https://github.com/user-attachments/assets/d0425d77-03bc-47d5-9e78-4639945d4002">
