### ISSUE TITLE
View Communities with uploaded iamge

### ISSUE THREAD

**Issue by altanborali16** [altanborali16/SWE574-Group2#161]
After closing issue #160 please change views on frontend on relevant pages

**Comment by altanborali16** [comment]
Closed with pr [#181](https://github.com/altanborali16/SWE574-Group2/pull/192)

**Comment by AliSerGok** [comment]
upload/show image improvements on createCommunity, communityPage, communityListOld pages are created. 
commıt number: c76d4f3a78656e40262b05ecec569dbfa6928a19

**Comment by AliSerGok** [comment]
closed with pr: [181](https://github.com/altanborali16/SWE574-Group2/pull/181)
