### ISSUE TITLE
Check frontend for app sizes and note them

### ISSUE THREAD

**Issue by altanborali16** [altanborali16/SWE574-Group2#162]

**Comment by EnesAkkal** [comment]
**Profile Page**
The badges does not look UI friendly in profile page, it needs to be fixed.
<img width="653" alt="image" src="https://github.com/user-attachments/assets/9f3ed8a0-d33b-4890-a1e8-d57661915bfd">

**Community Page**
The buttons needs to be re-positioned and badges should be fixed just like the profile page.
<img width="751" alt="image" src="https://github.com/user-attachments/assets/8e1ed81f-e266-43bb-a157-3483950a33e7">

**Comments**
This is how comments look like,  we can't see the half of the comment secition and we can't see the comment button at the bottom.
<img width="712" alt="image" src="https://github.com/user-attachments/assets/a7e07508-68ca-4323-81bb-ff3c53d182f2">

**My Communities Page**
We can't see all the listed communities, it needs to be fixed. 
<img width="712" alt="image" src="https://github.com/user-attachments/assets/0156f6ef-8208-412e-8248-ed52af732a2a">

**Posts with Images**
It does not look good when a post containts image, it needs to be fixed.
<img width="740" alt="image" src="https://github.com/user-attachments/assets/bf227603-f338-4771-b918-992aaa405dec">

**Template Creation**
We can't see the half of template creation.
<img width="719" alt="image" src="https://github.com/user-attachments/assets/68adf412-a429-448f-929b-8d1cc2d4e7db">

**Home Feed**
Posts under home feed will be fixed.
<img width="745" alt="image" src="https://github.com/user-attachments/assets/89e300d0-71b9-4d59-b84d-0c97a93daefe">

**Comment by EnesAkkal** [comment]
I have tried to fix the issue with commit number c1adab15fc9e9821a6b227b9104ed3b374f69b65. However, I and @altanborali16 had different UI views for the mobile. We'll check it later on

**Comment by altanborali16** [comment]
Thank you for your contributions @EnesAkkal , I believe there are lots of commits so I wont add them here, but I tested them and everything looks great
