### ISSUE TITLE
introduce-custom-enum-field-type

### ISSUE THREAD

**Issue by kotobusdriver** [altanborali16/SWE574-Group2#184]
This implementation assumes that all operations for enum options are done in UI; the BE only keeps the parameters provided by the user during template creation. That is the BE stores the parameters composed by the UI translated from the user input in a template field. 

When the user wants to have custom enum types in the template (eg., user sets a list of dog breeds one by one), the UI must include these options (= dog breeds) as parameters in a JSON, something like an array of options to display to the user. 

When creating a post, the value field for PostContent object must be set to the index of the option in the array in the UI (eg., you have 4 dog breeds defined in the template; when creating a post, user selects breed 3; so 3 should go in the value field of the PostContent).

When displaying posts, the UI should render the correct option from the value field of the PostContent.

Please consider this and suggest how the BE can improve the life of the FE developer )

Pull request - https://github.com/altanborali16/SWE574-Group2/pull/186

**Comment by efestrikesback** [comment]
Putting string "ENUM" in an enum does not help at all
