### ISSUE TITLE
Create use case scenarios and diagrams

### ISSUE THREAD

**Issue by kotobusdriver** [altanborali16/SWE574-Group2#25]
- [x] Write user scenarios based on current requirements specification
- [ ] Write user scenarios based on new system features (in consultation with backend/frontend teams)
- [x] Create activity diagrams to illustrate use cases to the customer
- [x] Upload use case scenarios and diagrams to Wiki at https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios

**Comment by AliSerGok** [comment]
Write user scenarios based on current requirements specification
 Create activity diagrams to illustrate use cases to the customer
 Upload use case scenarios and diagrams to Wiki at https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios
