### ISSUE TITLE
Create forgot password page on front end

### ISSUE THREAD

**Issue by EnesAkkal** [altanborali16/SWE574-Group2#30]
Create a forgot password page on the front end. The page will have the following fields.

- Email
- New Password

**Comment by efestrikesback** [comment]
Do you know if this is a mandatory requirement? If not we should not implement it considering our backend has no corresponding service for it.

**Comment by EnesAkkal** [comment]
Forgot password feature implementation is planned once all the tasks are completed.

**Comment by efestrikesback** [comment]
We will not have this feature atm.
