### ISSUE TITLE
Describe individual contribution

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#47]
On  [wiki page](https://github.com/altanborali16/SWE574-Group2/wiki/Individual-Contributions) please fill your part

Then comment on this issue "DONE", I will close the issue once everybody completes their work.

Suzan Hoca's notes:

While preparing your report, provide the necessary references to your work (e.g., pull requests, issues, etc.) on GitHub as you have to substantiate any reported work. Each member should add a subsection under the individual contributions section in the following format.

		Member: (Your name)

		Responsibilities: A general description of the responsibilities assigned to you.

		Main contributions: The overall description of your contributions to the project for

**Comment by altanborali16** [comment]
I added my contributions on [wiki Milestone 1 Report](https://github.com/altanborali16/SWE574-Group2/wiki/Milestone-1-Report) DONE

**Comment by EnesAkkal** [comment]
I filled my section on wiki regarding milestone 1 report.

**Comment by kotobusdriver** [comment]
I filled my Individual Contribution section in milestone 1 report on Wiki.

**Comment by AliSerGok** [comment]
I added my contributions on [milestone 1 report](https://github.com/altanborali16/SWE574-Group2/wiki/Milestone-1-Report) DONE

**Comment by efestrikesback** [comment]
I filled my Individual Contribution section in the milestone 1 report on Wiki.

**Comment by Stroggification** [comment]
I filled my individual contributions in wiki under milestone report 1. Done.

**Comment by efestrikesback** [comment]
created a new branch for the content update, the merge pull request is ready.

https://github.com/altanborali16/SWE574-Group2/pull/77
