### ISSUE TITLE
Finish previous term's must features (Frontend)

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#56]

**Comment by efestrikesback** [comment]
@altanborali16 you may open sub-tasks to show your work.

**Comment by altanborali16** [comment]
Issues #93 #92 #91 are created as subtasks

**Comment by efestrikesback** [comment]
@altanborali16 please close this issue after completing advanced search integration

**Comment by altanborali16** [comment]
Advanced search has been implemented, so now closing the issue
