### ISSUE TITLE
Implement badge mechanism (Frontend)

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#57]

**Comment by altanborali16** [comment]
Issue closed with [Commit 9969627](https://github.com/altanborali16/SWE574-Group2/commit/9969627d36a32eaa5a97bbb93095cec110d52d93)  for profile page and [Commit 94170e2
](https://github.com/altanborali16/SWE574-Group2/commit/94170e21a411444a31448b68c4b451d05f5f6de4) for community page.
