### ISSUE TITLE
Badge mechanism UI/UX design

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#60]
Create UI/UX designs for the badge system.

**Comment by EnesAkkal** [comment]
The badge system design for both community-based and user-specific achievements has been completed. Both types of badges will be displayed on the community page as we discussed with @altanborali16 earlier.


<img width="815" alt="image" src="https://github.com/user-attachments/assets/94c518c0-00cd-4145-be52-b9fe7c6685c2">
