### ISSUE TITLE
Scenarios and mockups, creation and organisation of existing ones

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#62]

**Comment by AliSerGok** [comment]
User Scenarios are created on [wiki with yana](https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios#use-case-scenarios-and-activity-diagrams)

**Comment by EnesAkkal** [comment]
I've revised and added some of the mockup designs as we discussed before.

### New Mockups

1. Create Post
<img width="733" alt="image" src="https://github.com/user-attachments/assets/3bc761fc-e4d4-4c74-beae-19a0ce79d7e8">

2. Create Template
<img width="733" alt="image" src="https://github.com/user-attachments/assets/7b9a7a3a-ef2a-4a48-9d43-78e24b75b147">

3. Home Feed
<img width="733" alt="image" src="https://github.com/user-attachments/assets/2cadbaab-cd87-4561-8884-7066a2f0196f">

### Revision on the Existing Ones

1. Community Page 
This is how our community page looks like in our designs. We didn't have user-specific badges in our previous designs. 
<img width="733" alt="image" src="https://github.com/user-attachments/assets/b9224412-f025-4a03-8caa-33248636eb28">
