### ISSUE TITLE
Create mockups 

### ISSUE THREAD

**Issue by kotobusdriver** [altanborali16/SWE574-Group2#9]
- [x] Hold a front-end design meeting and document front-end design choices.
- [ ] Based on the requirements, create mockups to illustrate community-specific features, **by October 7.**  Demonstrate that access to community-specific features remains user-friendly on mobile clients (since we're aiming at making a PWA).

**Comment by altanborali16** [comment]
I just created a login page just to show how it feels on website and webapp.

So in the website on desktop it is shown as below : 
![image](https://github.com/user-attachments/assets/59d2fa72-b3cf-446b-ab91-64124dcb8c05)

As you can see there is a download button which creates an app on desktop show in below : 

![image](https://github.com/user-attachments/assets/9d721e7b-e8b0-4876-aff0-d4cec2fa218c)

And also an shortcut to desktop 

![image](https://github.com/user-attachments/assets/e797ff38-f32f-492d-9e54-0816a1f02163)


On the mobile section this is how it looks on website (chorome safari etc)
![WhatsApp Image 2024-10-06 at 13 50 51](https://github.com/user-attachments/assets/c9e14237-a003-4144-baf7-86963a776ec8)

And after you download it to your main screen 
![WhatsApp Image 2024-10-06 at 13 50 50](https://github.com/user-attachments/assets/3f2ab6cb-9ea5-4300-83c2-ca9eb5026c31)


This is how app seen by user 

![WhatsApp Image 2024-10-06 at 13 50 49](https://github.com/user-attachments/assets/b8da86b4-e867-45ec-aa30-d832ccf06ae8)

So there is no url etc

**Comment by EnesAkkal** [comment]
You can see some of the designed screens below. 

**Login / Register Screen**

<img width="795" alt="image" src="https://github.com/user-attachments/assets/e8ee1088-fa69-4690-badb-6f0ec2df4cb8">


**Communities Screen**

<img width="796" alt="image" src="https://github.com/user-attachments/assets/ca613255-61ae-40c9-a57d-56919fb78ae4">

**Create Community Screen**

<img width="795" alt="image" src="https://github.com/user-attachments/assets/732329d4-88f0-49e9-91e1-32cfbc3d42a6">

**Community Feed Screen**

<img width="787" alt="image" src="https://github.com/user-attachments/assets/7af34539-48c0-44db-a896-515dfc69dda4">
