### ISSUE TITLE
Implement cookies and local storage utilisation

### ISSUE THREAD

**Issue by altanborali16** [altanborali16/SWE574-Group2#95]
Store authkey etc for a duration so even if the browser closed when user enters the website login should be successfull

**Comment by efestrikesback** [comment]
@altanborali16 's frontend end uses cookies. 

@efestrikesback's uses local storage only for simplicity. 

@kotobusdriver could you please add this as a decision?  "We have decided to implement both client storage techniques to guarantee delivery"
