### ISSUE TITLE
Check the progress and readiness for the presentation.

### ISSUE THREAD

**Issue by efestrikesback** [altanborali16/SWE574-Group2#97]

**Comment by altanborali16** [comment]
Checked yana's branch we will have discussion on current backend and frontend, also will talk about new frontend. Meeting set date 1/11/2024. @kotobusdriver

**Comment by altanborali16** [comment]
We will have a meeting with @efestrikesback 2/11/2024 for status of backend.

**Comment by altanborali16** [comment]
@AliSerGok and @EnesAkkal can you please inform us about the status on designs and workflow diagrams ?

I saw comment on issue #62  from @AliSerGok if it is done can you move it to in review on project ?

**Comment by altanborali16** [comment]
I changed the due date of the "milestone iteration" (on project section) to 4/11/2024. Please add your issues to [status board](https://github.com/users/altanborali16/projects/1/views/2?sliceBy%5Bvalue%5D=Milestone+Iteration) for better tracking and correct iteration, also make sure that all the issues are on correct milestone, status etc...

@efestrikesback @AliSerGok @EnesAkkal @kotobusdriver @Stroggification

**Comment by efestrikesback** [comment]
I am super busy to track the status board, if an issue is open it means I am working on it.

**Comment by EnesAkkal** [comment]
The creation of new mockup designs and the revision of existing ones have been completed. You can view the mockups [here](https://github.com/altanborali16/SWE574-Group2/issues/62#issuecomment-2453413215)

**Comment by AliSerGok** [comment]
issue [#62](https://github.com/altanborali16/SWE574-Group2/issues/62) has been placed in review status

**Comment by AliSerGok** [comment]
Event Flow diagrams were created at [Event Flow Diagrams](https://github.com/altanborali16/SWE574-Group2/wiki/Designs,-diagrams,-and-use-case-scenarios#event-flow-diagrams)

issue [#63 ](https://github.com/altanborali16/SWE574-Group2/issues/63) has been placed in review status

**Comment by efestrikesback** [comment]
thanks frens.
